# Generated by Django 4.2 on 2026-05-29 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_lote_numero_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_produccion', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField()),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='EN_PROCESO', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batidos', to='catalogo.productoterminado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_produccion', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCompensatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_afectado', models.CharField(max_length=50)),
                ('id_afectado', models.PositiveIntegerField()),
                ('datos_originales', models.JSONField(blank=True, default=dict)),
                ('datos_corregidos', models.JSONField(blank=True, default=dict)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LoteProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_ESPERA', 'En espera'), ('EN_PUNTO_DE_VENTA', 'En punto de venta')], default='EN_ESPERA', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_produccion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_despacho', models.DateField(blank=True, null=True)),
                ('batido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_pt', to='produccion.batido')),
            ],
            options={
                'ordering': ['fecha_produccion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleBatido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.batido')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventario.lote')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.materiaprima')),
            ],
        ),
    ]
