# Generated by Django 6.0.5 on 2026-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batido',
            name='fecha_recepcion_huevo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batido',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='batido',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loteproductoterminado',
            name='cantidades_por_talla',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loteproductoterminado',
            name='cup_cake',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loteproductoterminado',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loteproductoterminado',
            name='planchas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loteproductoterminado',
            name='porcionada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
