# Generated by Django 6.0.5 on 2026-05-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='numero_lote',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
