# Generated by Django 4.2 on 2026-06-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_lote_numero_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='inventario.bodega')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('bodega', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='inventario.zonabodega'),
        ),
    ]
