# Generated by Django 4.2 on 2026-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_zonas_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonabodega',
            name='capacidad_maxima',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Capacidad máxima en gramos o unidades (según MP)', max_digits=12),
        ),
    ]
