# Generated by Django 6.0.5 on 2026-05-29 14:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='catalogo.proveedor')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_presentacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.materiaprima')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.presentacion')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='recepcion.ordencompra')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('confirmada', models.BooleanField(default=True)),
                ('justificacion_vencimiento', models.TextField(blank=True)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='recepcion.ordencompra')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
