# Generated by Django 4.2 on 2026-06-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10),
        ),
    ]
