# Generated by Django 6.0.5 on 2026-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_add_parcial_estado_and_cantidad_recibida'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionmercancia',
            name='accion_correctiva',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='cantidad_rechazada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='fecha_ingreso_planta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='libre_infestacion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='libre_material_extrano',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='producto_aplicado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='responsable_proceso',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='responsable_verificacion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='rotulacion_adecuada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='sin_aperturas_rupturas',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
