# Generated by Django 4.2 on 2026-06-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_numero', models.CharField(blank=True, help_text='Número de WhatsApp (incluir código país, ej: +573001234567)', max_length=20)),
                ('email_gerencia', models.EmailField(blank=True, max_length=254)),
                ('email_produccion', models.EmailField(blank=True, max_length=254)),
                ('dias_umbral_vencimiento', models.PositiveIntegerField(default=7, help_text='Días antes del vencimiento para generar alerta')),
            ],
            options={
                'verbose_name_plural': 'Configuración de Alertas',
            },
        ),
    ]
