# Generated by Django 6.0.5 on 2026-05-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('simbolo', models.CharField(max_length=10, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('punto_reorden', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_minimos_vencimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('GALLETERIA', 'Galletería'), ('TORTA', 'Torta'), ('BIZCOCHO', 'Bizcocho'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('condicion_almacenamiento', models.CharField(choices=[('AMBIENTE', 'Temperatura ambiente'), ('REFRIGERACION', 'Refrigeración'), ('CONGELADO', 'Congelado')], default='AMBIENTE', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('proveedores', models.ManyToManyField(blank=True, related_name='materias_primas', to='catalogo.proveedor')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_primas', to='catalogo.unidadmedida')),
            ],
            options={
                'verbose_name': 'Materia prima',
                'verbose_name_plural': 'Materias primas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('vida_util_dias', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_terminados', to='catalogo.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto terminado',
                'verbose_name_plural': 'Productos terminados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('factor_conversion', models.DecimalField(decimal_places=4, max_digits=14)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='catalogo.materiaprima')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentaciones', to='catalogo.unidadmedida')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['nombre'],
                'unique_together': {('materia_prima', 'nombre')},
            },
        ),
    ]
