# Generated by Django 4.2 on 2026-06-05 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('RECEPCION_CREADA', 'Recepción creada'), ('TRASLADO', 'Traslado'), ('BATIDO_CREADO', 'Batido creado'), ('COMPENSATORIO', 'Compensatorio'), ('DESPACHO', 'Despacho'), ('USUARIO_DESACTIVADO', 'Usuario desactivado')], max_length=50)),
                ('detalle', models.JSONField(default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
